# REUSE.toml
# Part of ReusePkgTemplates

version = 1

# project infrastructure
[[annotations]]
path = [
    ".gitattributes",
    ".gitignore",
    ".github/**",
    ".vscode/**",
    ".licensing/**",
    ".*.yml",
    ".drone.star",
    "CITATION.bib",
    "CODEOWNERS",
    ".JuliaFormatter.toml",
    "Project.toml",
    "Manifest.toml",
    "docs/make.jl",
    "docs/Project.toml",
    "docs/Manifest.toml",
    "test/Project.toml",
    "test/Manifest.toml",
    "scripts/Project.toml",
    "scripts/Manifest.toml",
    "templates/**"
]
precedence = "closest"
SPDX-FileCopyrightText = "2026 Guido Wolf Reichert and contributors"
SPDX-License-Identifier = "0BSD"

# documentation assets
[[annotations]]
path = ["docs/src/assets/**"]
precedence = "closest"
SPDX-FileCopyrightText = "2026 Guido Wolf Reichert and contributors"
SPDX-License-Identifier = "CC-BY-SA-4.0"

# documentation source texts
[[annotations]]
path = ["README.md", "docs/*.md", "docs/src/**/*.md"]
precedence = "closest"
SPDX-FileCopyrightText = "2026 Guido Wolf Reichert and contributors"
SPDX-License-Identifier = "CC-BY-SA-4.0"
